apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "madana-communityhub.fullname" . }}
  labels:
    {{- include "madana-communityhub.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "madana-communityhub.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "madana-communityhub.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "madana-communityhub.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerport }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /login
              port: http
          readinessProbe:
            httpGet:
              path: /login
              port: http
          env:
           - name: INSTANCENAME
             value: {{ include "madana-communityhub.fullname" . }}
           - name: CERTIFICATE
             value: {{ .Values.environment.certificate | quote }}
           - name: RESTURI
             value: {{ .Values.environment.resturi | quote }}
           - name: GOOGLECAPTCHA_SECRETKEY
             value: {{ .Values.environment.googlecaptcha_secretkey | quote }}
           - name: GOOGLECAPTCHA_WEBSITEKEY
             value: {{ .Values.environment.googlecaptcha_websitekey | quote }}
           - name: GOOGLEANALYTICS_TRACKINGID
             value: {{ .Values.environment.googleanalytics_trackingid | quote }}
           - name: STATUSPAGE_PAGEID
             value: {{ .Values.environment.statuspage_pageid | quote }}
           - name: STATUSPAGE_PAGELINK
             value: {{ .Values.environment.statuspage_pagelink | quote }}
           - name: MEDIUM_FEEDURL
             value: {{ .Values.environment.medium_feedurl | quote }}
           - name: SENTRY_DSN
             value: {{ .Values.Sentry.DSN }}
           - name: SENTRY_RELEASE
             value: {{ .Values.Sentry.RELEASE }}
           - name: SENTRY_ENVIRONMENT
             value: {{ .Values.Sentry.ENVIRONMENT }}
           - name: JAVA_OPTS
             value: "-DINSTANCENAME={{ include "madana-communityhub.fullname" . }} -DCERTIFICATE={{ .Values.environment.certificate}} -DRESTURI={{ .Values.environment.resturi}} -DGOOGLECAPTCHA_SECRETKEY={{ .Values.environment.googlecaptcha_secretkey }} -DGOOGLECAPTCHA_WEBSITEKEY={{ .Values.environment.googlecaptcha_websitekey  }} -DGOOGLEANALYTICS_TRACKINGID={{ .Values.environment.googleanalytics_trackingid }} -DSENTRY_DSN={{ .Values.Sentry.DSN }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
