{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "madana-communityhub.serviceAccountName" . }}
  labels:
{{ include "madana-communityhub.labels" . | nindent 4 }}
{{- end -}}
